CREATE TABLE "article" ("id" INTEGER PRIMARY KEY  NOT NULL , "title" CHAR NOT NULL  UNIQUE , "create_date" DATETIME NOT NULL , "last_update" DATETIME NOT NULL , "posted" BOOL NOT NULL  DEFAULT 0, "cate_name" VARCHAR NOT NULL , "permalink" CHAR NOT NULL );
CREATE TABLE "atmap" ("id" INTEGER PRIMARY KEY  NOT NULL , "article_id" INTEGER NOT NULL , "tag_id" INTEGER NOT NULL , "cate_name" CHAR NOT NULL );
CREATE TABLE "tag" ("id" INTEGER PRIMARY KEY  NOT NULL , "name" VARCHAR NOT NULL , "count" INTEGER NOT NULL  DEFAULT 1);
